export const FETCH_POST_REQUESTED = 'FETCH_POST_REQUESTED';
export const FETCH_POST_SUCCEED = 'FETCH_POST_SUCCEED';
export const FETCH_MORE_POST_REQUESTED = 'FETCH_MORE_POST_REQUESTED';
export const FETCH_MORE_POST_SUCCEED = 'FETCH_MORE_POST_SUCCEED';
export const FETCH_POST_FAILED = 'FETCH_POST_FAILED';
export const FETCH_POST_RESETED = 'FETCH_POST_RESETED';

export const FETCH_TRENDING_POST_REQUESTED = 'FETCH_TRENDING_POST_REQUESTED';
export const FETCH_TRENDING_POST_SUCCEED = 'FETCH_TRENDING_POST_SUCCEED';
export const FETCH_TRENDING_POST_FAILED = 'FETCH_TRENDING_POST_FAILED';
export const FETCH_TRENDING_POST_RESETED = 'FETCH_TRENDING_POST_RESETED';

export const SINGLE_POST_REQUESTED = 'SINGLE_POST_REQUESTED';
export const SINGLE_POST_SUCCEED = 'SINGLE_POST_SUCCEED';
export const SINGLE_POST_FAILED = 'SINGLE_POST_FAILED';
export const SINGLE_POST_RESETED = 'SINGLE_POST_RESETED';
