export const FETCH_TAG_REQUESTED = 'FETCH_TAG_REQUESTED';
export const FETCH_TAG_SUCCEED = 'FETCH_TAG_SUCCEED';
export const FETCH_TAG_FAILED = 'FETCH_TAG_FAILED';
export const FETCH_TAG_RESETED = 'FETCH_TAG_RESETED';

export const SINGLE_TAG_REQUESTED = 'SINGLE_TAG_REQUESTED';
export const SINGLE_TAG_SUCCEED = 'SINGLE_TAG_SUCCEED';
export const SINGLE_TAG_FAILED = 'SINGLE_TAG_FAILED';
export const SINGLE_TAG_RESETED = 'SINGLE_TAG_RESETED';
