export const SINGLE_USER_REQUESTED = 'SINGLE_USER_REQUESTED';
export const SINGLE_USER_SUCCEED = 'SINGLE_USER_SUCCEED';
export const SINGLE_USER_FAILED = 'SINGLE_USER_FAILED';
export const SINGLE_USER_RESETED = 'SINGLE_USER_RESETED';
